Module4 task1
htmlacademy-javascript/2386079-kekstagram-29 pull request #3
Opened 2024-01-13 12:23 UTC by takustova

2024-01-13 13:31 UTC, wonderjs requested changes

2024-01-13 13:31 UTC, wonderjs commented on js/main.js
> +const message = [
Тут нужно обратить внимание на 2 критерия:
1) [Б5.](https://up.htmlacademy.ru/javascript/29/criteries#b5) Массивы названы существительными во множественном числе.
2) [Б7.](https://up.htmlacademy.ru/javascript/29/criteries#b7) Названия констант (постоянных значений, известных до начала выполнения программы) написаны прописными (заглавными) буквами.
Те правильный вариант - `MESSAGES`

2024-01-13 13:31 UTC, wonderjs commented on js/main.js
> +const name = [
Аналогично, [Б5.](https://up.htmlacademy.ru/javascript/29/criteries#b5) + [Б7.](https://up.htmlacademy.ru/javascript/29/criteries#b7) - `NAMES`

2024-01-13 13:31 UTC, wonderjs commented on js/main.js
> +  id: createRandomIdFromRange (),
Тут лишний пробельчик между названием функции и кавычками ее вызова

2024-01-13 13:31 UTC, wonderjs commented on js/main.js
> +const messages = Array.from({length: getRandomInteger(1, 2)}, getRandomArrayElement(message));
Внимательно читаем задание `Для формирования текста комментария — message — вам необходимо взять одно или два случайных предложения из представленных ниже:`
Те message у нас должна быть строка из одного или двух предложений. Сейчас у тебя это массив из 1 или 2 элементов, преобразовать массив в строку мы можем с помощью метода [join](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/join)

2024-01-13 13:31 UTC, wonderjs commented on js/main.js
> +  message: messages,
Сейчас у всех комментариев, которые мы будем создавать message будет одинаковый, тк ты его создала и записала в переменную вне функции `createComments`. Если перенести внутрь, то при каждом вызове будет создаваться свой.

2024-01-13 13:31 UTC, wonderjs commented on js/main.js
> +const comments = Array.from({length: getRandomInteger(0, 30)}, createComments);
Аналогично, для каждого созданного объекта  фотографии будет всегда одинаковые комментарии, давай сделаем разные, перенеси внутрь функции, где создаешь объект

2024-01-13 13:31 UTC, wonderjs commented on js/main.js
> +const createObject = () => ({
Старайся давать более осознанные названия функциям и переменных, чтобы по ним было понятно что это и не используй object и array в названиях. Лучше `createPhoto`

2024-01-13 13:31 UTC, wonderjs commented on js/main.js
> +const objects = Array.from({length: 25}, createObject);
1) Не используем objects - лучше `photos`
2) Знакомимся с ещё одним критерием [Д19.](https://up.htmlacademy.ru/javascript-individual/1/criteries#d19) В коде не используются «магические значения», под каждое из них заведена отдельная переменная, названная как константа. 
25 - в константу

2024-01-13 13:31 UTC, wonderjs commented on js/main.js
> +  url: `photos/${getRandomInteger(1, 25)}.jpg`,
Сейчас существует большая вероятность, что фотографии и тебя будут дублироваться и не совпадать с id. Чтобы этого избежать, мы можем использовать силу метода [Array.from](https://doka.guide/js/array-from/)
Первый параметр `{length: 25}` - это объект, на основе которого создаётся массив.
Второй параметр - `createObject` - функция преобразования элемента перед его добавлением в массив
Рассмотрим подробнее описание метода и обратим внимание на функцию, которая будет применяться к каждому элементу массива https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/from 
Тк это аналог метода map, то в качестве параметров функции туда всегда приходит сам элемент и его индекс, те наша запись 
`const objects = Array.from({length: 25}, createObject);`
это на самом деле сокращенный вариант такой записи
`const objects = Array.from({length: 25}, (item, index) => createObject(item, index));`
И index у нас меняется от 0 до 24, а id для фото и ее url должен содержать число от 1 до 25, те мы можем немного преобразовать наш текущий вариант и сразу передавать внутрь функции createObject нужные нам значения от 1 до 25:
`const objects = Array.from({length: 25}, (item, index) => createObject(index + 1));`
Останется только при определении функции `createObject` добавить параметр id и использовать его внутри.

2024-01-13 17:57 UTC, wonderjs requested changes

2024-01-13 17:57 UTC, wonderjs commented on index.html
> +  <script src="main.js"></script>
Файл `main.js` у нас лежит в папке `js`, поэтому не забываем прописывать полный путь `src="./js/main.js"` и тип модуль `type="module" `

2024-01-13 17:57 UTC, wonderjs commented on js/main.js
> +function createRandomIdFromRange (min, max) {
Знакомимся ещё с одним критерием [Д5.](https://up.htmlacademy.ru/javascript/29/criteries#d5) Все функции объявлены единообразно. 
Те по дефолту мы все функции определяем через "стрелочный" вариант, если нам понадобится, чтобы функция всплывала, тогда используем вариант через ключевое слово `function`

2024-01-13 17:57 UTC, wonderjs commented on js/main.js
> +  const createComments = () => {
Функцию `createComments` лучше вынести из `createPhoto`

2024-01-13 17:57 UTC, wonderjs commented on js/main.js
> +    const messagesInComment = Array.from({length: getRandomInteger(1, 2)}, getRandomArrayElement(MESSAGES));
Предыдущий вариант (messages) названия этой переменной был более корректный, тк в результате у нас получался массив. 
Есть ошибка в передаче второго параметра в функцию `Array.from`, тк нам нужно вызывать функцию getRandomArrayElement с определенным параметром (а не с дефолтными элемент и индекс), то правильно будет так: 
`const messages = Array.from({length: getRandomInteger(1, 2)}, () => getRandomArrayElement(MESSAGES));`
Можешь ещё посмотреть описание метода `map` для лучшего понимая механизма работы `Array.from`

2024-01-13 17:57 UTC, wonderjs commented on js/main.js
> +    const message = messagesInComment.join(', ');
тут можно кстати записать всё в одну строку, без создания промежуточной переменной:
`const message = Array.from({length: getRandomInteger(1, 2)}, () => getRandomArrayElement(MESSAGES)).join(' ');`
Те сначала создастся массив и потом сразу преобразуется в строку

2024-01-13 17:57 UTC, wonderjs commented on js/main.js
> +const createPhoto = () => {
Вот тут был ключевой момент, при вызове `createPhoto` мы теперь передаем id, нужно добавить этот параметр и использовать:
```
const createPhoto = (id) => {
  const comments = Array.from({length: getRandomInteger(0, 30)}, createComments);

  return {
    id: id,
    url: `photos/${id}.jpg`,
    description: 'Фотография на память',
    likes: getRandomInteger(15, 200),
    comments: comments,
  };
};
```

2024-01-14 13:56 UTC, takustova commented on js/main.js
> +  const createComments = () => {
Ок, это я из прошлого коммента неправильно поняла, что именно нужно перенести внутрь функции createPhoto

2024-01-14 17:38 UTC, takustova commented on js/main.js
> +const createPhoto = () => {
Тут у меня вопросы)

1. Мы будем передавать id при вызове функции вручную, или id генерируется другой фукцией? 
2. И для чего мы вообще передаем id?
3. Из задания неочевидно, что id и число в url должны совпадать – почему это так?

2024-01-14 17:44 UTC, takustova commented on js/main.js
> +    const messagesInComment = Array.from({length: getRandomInteger(1, 2)}, getRandomArrayElement(MESSAGES));
Разве можно и массиву (который мы созданием с array.from), и строке из его объектов (.join) присвоить одинаковое название? То есть и тут, и там messages.

2024-01-14 18:16 UTC, wonderjs commented on js/main.js
> +    const messagesInComment = Array.from({length: getRandomInteger(1, 2)}, getRandomArrayElement(MESSAGES));
Не поняла, откуда взялось одинаковое значение? Итоговый вариант у нас будет выглядеть так:
```
const createComments = () => {
  const message = Array.from({length: getRandomInteger(1, 2)}, () => getRandomArrayElement(MESSAGES)).join(' ');

  return {
    id: createRandomIdFromRange(),
    avatar: `img/avatar-${getRandomInteger(1, 6)}.svg`,
    message: message,
    name: getRandomArrayElement(NAMES)
  };
};
```
Те в `message` мы создаем массив и потом сразу преобразуем его в строку без создания промежуточной переменной `messages`. Можно конечно оставить в 2 этапа, но это только съест немного места в памяти для создания переменной `messages`:
```
const createComments = () => {
  const messages = Array.from({length: getRandomInteger(1, 2)}, () => getRandomArrayElement(MESSAGES))
  const message = messages.join(' ');

  return {
    id: createRandomIdFromRange(),
    avatar: `img/avatar-${getRandomInteger(1, 6)}.svg`,
    message: message,
    name: getRandomArrayElement(NAMES)
  };
};
```

2024-01-14 18:20 UTC, wonderjs commented on js/main.js
> +const createPhoto = () => {
id мы передаем при вызове, мы сами его определили. Понимаешь ли ты механизм работы функций для массивов, типо map или forEach? Почитай, разбери на примерах
```
const photos = Array.from({length: PHOTOS_COUNT}, (item, index) => createPhoto(index + 1));
```
id мы передаем так чтобы его значение было строго от 1 до 25, тк по заданию что для id, что url у нас не должны повторяться значения. Те проще всего задавать их одинаковыми
```
id, число — идентификатор опубликованной фотографии. Это число от 1 до 25. Идентификаторы не должны повторяться.

url, строка — адрес картинки вида photos/{{i}}.jpg, где {{i}} — это число от 1 до 25. Адреса картинок не должны повторяться.
```

2024-01-15 10:49 UTC, wonderjs commented on js/main.js
> +  const messages = Array.from({length: getRandomInteger(1, 2)}, () => getRandomArrayElement(MESSAGES)).join(' ');
Только здесь у нас теперь уже не массив, а строка (ведь мы убрали промежуточную переменную `messages`), так что просто `message`

2024-01-15 10:49 UTC, wonderjs commented on js/main.js
> +    id: createRandomIdFromRange(1, 1000),
Здесь кстати можно просто использовать функцию `getRandomInteger`, а `createRandomIdFromRange` просто удалить

2024-01-15 10:52 UTC, takustova commented on js/main.js
> +    id: createRandomIdFromRange(1, 1000),
А в задании:

> У каждого комментария есть идентификатор — id — любое число. Идентификаторы не должны повторяться.

В getRandomInteger они могут повторяться. Или неправильно понимаю?

2024-01-15 10:54 UTC, wonderjs commented on js/main.js
> +    id: createRandomIdFromRange(1, 1000),
да, могут, но у нас нет особых условий для коммент id, так что в данном случае можем упростить.

2024-01-15 10:56 UTC, merged